name: main-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - name: Login to DockerHub
        run : echo ${{ secrets.DOCKERHUB_PWD }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Build new image
        run : docker build -t floardbot -f Dockerfile .
      - name: Push image to DockerHub
        run : docker push ${{ secrets.DOCKERHUB_LOGIN }}/floardbot
      - name: Logout from DockerHub
        run : docker logout
